//! This module is responsible for providing the interface for fetching the command signatures.
//! It abstracts away the underlying directory hierarchy. We organize the command signatures to
//! keep autogenerated specs separate from hand-written ones. However, the caller shouldn't need to
//! know that detail, and so we use this module to "flatten" the contents of
//! json/autogenerated/**/*.json and present an API to lookup command signatures by name only.
use std::borrow::Cow;

/// Exclude the autogenerated subdirectory. Including it here would expose it via its relative
/// path, e.g. `autogenerated/powershell/*.json`, which is not the API we want to expose to the
/// caller. Instead, have a separate struct handle those assets in the subdirectory.
#[derive(rust_embed::RustEmbed)]
#[folder = "json"]
#[exclude = "autogenerated/*"]
#[exclude = "overrides/*"]
struct ManualAssets;

/// Note that each subdirectory needs its own RustEmbed struct in order to logically "flatten" its
/// contents into a single namespace. Our custom `Assets` struct will handle "dispatching" to the
/// concrete RustEmbed struct.
#[derive(rust_embed::RustEmbed)]
#[folder = "json/autogenerated/powershell"]
struct PowershellAutogeneratedAssets;

/// This is a wrapper around the multiple RustEmbed structs that provides a single namespace for
/// accessing command signatures by name, abstracting away the underlying directory hierarchy.
pub(super) struct Assets;

impl Assets {
    pub(super) fn get(file_path: &str) -> Option<rust_embed::EmbeddedFile> {
        ManualAssets::get(file_path).or_else(|| PowershellAutogeneratedAssets::get(file_path))
    }

    pub(super) fn iter() -> impl Iterator<Item = Cow<'static, str>> {
        ManualAssets::iter().chain(PowershellAutogeneratedAssets::iter())
    }

    #[cfg(test)]
    pub(super) fn names() -> impl Iterator<Item = &'static str> {
        ManualAssets::names()
            .chain(PowershellAutogeneratedAssets::names())
            .copied()
    }
}

/// Iterates over the names of all known command signatures.
#[cfg(test)]
pub(super) fn all_signature_names() -> impl Iterator<Item = &'static str> {
    Assets::names().filter_map(|name| name.strip_suffix(".json"))
}
