use std::borrow::Cow;

#[derive(rust_embed::RustEmbed)]
#[folder = "json"]
#[exclude = "autogenerated/*"]
#[exclude = "overrides/*"]
struct ManualAssets;

#[derive(rust_embed::RustEmbed)]
#[folder = "json/autogenerated/powershell"]
struct PowershellAutogeneratedAssets;

pub(super) struct Assets;

impl Assets {
    pub(super) fn get(file_path: &str) -> Option<rust_embed::EmbeddedFile> {
        ManualAssets::get(file_path).or_else(|| PowershellAutogeneratedAssets::get(file_path))
    }

    pub(super) fn iter() -> impl Iterator<Item = Cow<'static, str>> {
        ManualAssets::iter().chain(PowershellAutogeneratedAssets::iter())
    }

    #[cfg(test)]
    pub(super) fn names() -> impl Iterator<Item = &'static str> {
        ManualAssets::names()
            .chain(PowershellAutogeneratedAssets::names())
            .copied()
    }
}

/// Iterates over the names of all known command signatures.
#[cfg(test)]
pub(super) fn all_signature_names() -> impl Iterator<Item = &'static str> {
    Assets::names().filter_map(|name| name.strip_suffix(".json"))
}
