name: CI

on:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@1.85
      with:
        components: rustfmt, clippy
    - name: Run cargo fmt
      run: cargo fmt -p warp-command-signatures -p warp-completion-metadata --check
    - name: Run cargo clippy
      run: cargo clippy -p warp-command-signatures -p warp-completion-metadata --all-targets --all-features -- -D warnings
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@1.85
    - name: Run tests
      run: cargo test --verbose
